name = "jofams-smartdrive"
compatibility_date = "2026-08-01"
pages_build_output_dir = "."

# 아래 database_id는 D1 생성 후 실제 값으로 교체하세요.
[[d1_databases]]
binding = "DB"
database_name = "jofams-smartdrive-db"
database_id = "6d6ea7da-2b05-4e66-8b6a-c6924c900d75"
migrations_dir = "migrations"
