org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
# Cloudflare Pages 배포 주소로 변경하세요.
SMARTDRIVE_URL=https://jofams-smartdrive.pages.dev/

# Firebase/Google Cloud의 Web OAuth 2.0 Client ID
GOOGLE_WEB_CLIENT_ID=681909120668-ta7kbn8329nibom3qnuda81gk4v38r2n.apps.googleusercontent.com
GOOGLE_ANDROID_CLIENT_ID=681909120668-ub1ir3jvl5eg5trp0horgr77slg9i4ft.apps.googleusercontent.com
KNOWN_SIGNING_SHA1S=E0:35:0D:67:D9:0A:F4:CE:28:2F:5A:20:0E:2A:65:6D:E2:AF:D5:FD,0B:D8:16:EF:CF:46:87:BC:BD:7F:5A:D3:A2:6D:1C:1E:00:35:15:3D
org.gradle.caching=false
org.gradle.vfs.watch=false
org.gradle.daemon=true
